---
- name: Setup Web Server
  hosts: webserver
  become: yes

  tasks:
    - name: Install Apache
      yum:
        name: httpd
        state: present

    - name: Start Apache service
      service:
        name: httpd
        state: started
        enabled: yes

    - name: Create a web directory
      file:
        path: /var/www/html/demo
        state: directory
        owner: ec2-user
        group: ec2-user
        mode: '0755'

    - name: Deploy index.html from template
      template:
        src: templates/index.html.j2
        dest: /var/www/html/demo/index.html

